# Generated by Django 3.1.6 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20250328_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Aventure', 'Aventure'), ('Thriller', 'Thriller'), ('Fantastique', 'Fantastique'), ('Romance', 'Romance'), ('Horreur', 'Horreur'), ('Science-fiction', 'Science-fiction')], max_length=100),
        ),
    ]
