# Generated by Django 3.1.6 on 2025-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20250328_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Aventure', 'Aventure'), ('Thriller', 'Thriller'), ('Fantastique', 'Fantastique'), ('Romance', 'Romance'), ('Horreur', 'Horreur'), ('Science-fiction', 'Science-fiction'), ('Science', 'Science')], max_length=20),
        ),
    ]
